[general]
import = [
  "/usr/lib/node_modules/alacritty-themes/themes/Catppuccin-Macchiato.toml"
]

[font]
  size = 14
#  builtin_box_drawing = true
  [font.normal]
    family = "unifont"

[window]
  opacity = 0.7
  blur=true
  decorations = "None"
  title = "lily@lotus"
  dynamic_padding = true
  dynamic_title = false
  resize_increments = true
  [window.padding]
    x = 10
    y = 8


[colors]
  draw_bold_text_with_bright_colors = true
  transparent_background_colors=false
  
